repository: 

output: web
# this property is useful for conditional filtering of content that is separate from the PDF.

topnav_title: Slurm*O*Rama | Carina 
# this appears on the top navigation bar next to the home button

site_title: Slurm*O*Rama | Carina
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

company_name: Stanford Research Computing

# this appears in the footer
#repo: https://github.com/stanford-rc/nero

# This is the text in the top logo. For the value of modifier_class, see
# https://decanter.stanford.edu/component/identity-lockup/

lockup_line2: Slurm*O*Rama 
lockup_link: /index.html
lockup_line1: Research Computing
lockup_modifier_class: su-lockup--option-b

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      toc: false