repository: 

output: web
# this property is useful for conditional filtering of content that is separate from the PDF.

topnav_title: Slurm*O*Matic 
# this appears on the top navigation bar next to the home button

site_title: Slurm*O*Matic
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

company_name: Stanford Research Computing

# This is the text in the top logo. For the value of modifier_class, see
# https://decanter.stanford.edu/component/identity-lockup/

lockup_line2: SLURM*O*MATIC
lockup_link: /index.html
lockup_line1: Research Computing
lockup_modifier_class: su-lockup--option-b

# if you have forked this, please please change this to your google analytics ID
googleID : G-ZE47PKCRTK
# googleID : G-XXXXXX

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"